ignore_SD&CE: &base_config
  epochs: 30
  log_dir: results
  batch_size: 256
  path_row_config:
    train: [0, 2000000, 10]
    validation: [2000000, 3000000, 50]
    test: [3000000, 3100000, 250]
  model_config:
    lr: 0.0006
    input_shape: [64, 64, 2]
    num_db: 7
    convs_per_db: 2
    growth_rate: 16
    num_channels: 16
  loss_config:
    name: combined_loss
    loss_configs:
      - name: soft_dice
      - name: cross_entropy
    weights: [5.0, 0.05]

ignore_SD&WCE:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: soft_dice
      - name: cross_entropy
        beta: 0.75
    weights: [5.0, 0.05]

ignore_SD&BCE:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: soft_dice
      - name: cross_entropy
        beta: 0.75
        balanced: True
    weights: [5.0, 0.05]

ignore_SD&FL:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: soft_dice
      - name: focal
        gamma: 1.3
        beta: 0.75
    weights: [5.0, 0.05]

ignore_TL&CE:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: tversky
      - name: cross_entropy
    weights: [5.0, 0.05]

ignore_TL&WCE:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: tversky
      - name: cross_entropy
        beta: 0.75
    weights: [5.0, 0.05]

ignore_TL&BCE:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: tversky
      - name: cross_entropy
        beta: 0.75
        balanced: True
    weights: [5.0, 0.05]

TL&FL:
  <<: *base_config
  loss_config:
    name: combined_loss
    loss_configs:
      - name: tversky
      - name: focal
        gamma: 1.3
        beta: 0.75
    weights: [5.0, 0.05]