Focal: &base_config
  epochs: 30
  log_dir: results
  batch_size: 64
  path_row_config:
    train: [0, 3000000, 100]
    validation: [3000000, 4000000, 200]
    test:  [4000000, 4100000, 250]
  data_config:
    n_voxels: 64
    n_dim: 2
  model_config:
    lr: 0.0005
    input_shape: [64, 64, 2]
    num_db: 3
    convs_per_db: 2
    growth_rate: 32
    num_channels: 32
  loss_config:
    name: focal
    gamma: 2
    beta: 0.5
    balanced: False

FocalBalanced:
  <<: *base_config
  loss_config:
    name: focal
    gamma: 2
    beta: 0.5
    balanced: True