Focal: &base_config
  epochs: 30
  log_dir: results
  batch_size: 64
  path_row_config:
    train: [0, 2000000, 50]
    validation: [2000000, 3000000, 100]
    test:  [3000000, 3100000, 250]
  data_config:
    n_voxels: 64
    n_dim: 2
  model_config:
    lr: 0.0003
    input_shape: [64, 64, 2]
    num_db: 7
    convs_per_db: 2
    growth_rate: 16
    num_channels: 16
  loss_config:
    name: focal
    gamma: 1.3
    beta: 0.75
    balanced: False

FocalBalanced:
  <<: *base_config
  loss_config:
    name: focal
    gamma: 1.3
    beta: 0.75
    balanced: True