Euclidean: 
  epochs: 30
  log_dir: results
  batch_size: 64
  path_row_config:
    train: [0, 4000000, 10]
    validation: [1, 4000000, 200]
    test: [4000000, 5000000, 250]
  model_config:
    lr: 0.001
    input_shape: [64, 64, 3]
    num_db: 2
    convs_per_db: 3
    growth_rate: 16
    num_channels: 16
  loss_config:
    name: euclidean
