Focal: &base_config
  epochs: 30
  log_dir: results
  batch_size: 128
  path_row_config:
    train: [0, 2000000, 100]
    validation: [2000000, 3000000, 50]
    test: [3000000, 3100000, 250]
  model_config:
    lr: 0.0003
    input_shape: [64, 64, 2]
    num_db: 7
    convs_per_db: 2
    growth_rate: 16
    num_channels: 16
  loss_config:
    name: focal
    gamma: 1.3
    beta: 0.75
    weight: 0.01